language: node_js
node_js:
  - "10.15.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master
cache:
  directories:
    - "node_modules"

install: npm install
 
before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch false --browsers ChromeHeadless
